spring:
  profiles: dev
  application:
    name: order-service
  redis:
    host: 192.168.67.129
#    password: 123456
    port: 6379
    jedis:
      pool:
        max-active: 100 #最大连接数
        max-wait: 30000  #最大阻塞等待时间（负数代表没有限制）
        max-idle: 20 #最大空闲连接数
        min-idle: 0 #最小空闲连接数
    timeout: 3000 #连接超时
server:
  port: 8093

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/




