spring:
  profiles: dev
  application:
    name: order-service
  redis:
    host: 192.168.67.129
#    password: 123456
    port: 6379
    jedis:
      pool:
        max-active: 100 #最大连接数
        max-wait: 30000  #最大阻塞等待时间（负数代表没有限制）
        max-idle: 20 #最大空闲连接数
        min-idle: 0 #最小空闲连接数
    timeout: 3000 #连接超时
  session:
    store-type: redis # Session store type.
    redis:
      flush-mode: on_save # Sessions 刷新模式，on_save 保存时刷新
      namespace: spring:session # 命名空间
    timeout: 1800

server:
  servlet:
    session:
      timeout: 1800 # Session 超时时间，默认单位秒，也可以使用spring.session.timeout属性
  port: 8093

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/


logging:
  config: classpath:logback-spring.xml

sentry:
  dsn: http://ac5a2918ec064472a861066a5c3ddcdc@192.168.1.129:19000/4
  send-default-pii: true

