server:
  port: 8081

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.67.129:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    enabled: false  #因为父工程统一依赖了eureka,跟nacos注册中心冲突了,所以禁用掉eureka